include classpath("application.conf")

node-address {
  protocol = http
  host = sqs-local
  port = 9324
  context-path = ""
}

queues {
  stratus-notifications {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "stratus-notifications-dlq"
      maxReceiveCount = 3
    }
  }
  stratus-notifications-dlq {}
}